# Generated by Django 5.0 on 2023-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLmodel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('orignal_url', models.URLField(unique=True, verbose_name='URL')),
                ('new_url', models.CharField(max_length=200)),
            ],
        ),
    ]
