# Generated by Django 5.0 on 2023-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='orignal_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
